version: '3.7'

services:
  multiple_resources_postgres1sequelize:
    image: postgres:9.6-alpine
    ports:
      - published: 5435
        target: 5432
    environment:
      POSTGRES_DB: baby
      POSTGRES_USER: dont
      POSTGRES_PASSWORD: hurtme

  multiple_resources_kafka:
    image: confluentinc/cp-kafka:5.2.2
    ports:
      - published: 9092
        target: 9092
    depends_on:
      - multiple_resources_zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://multiple_resources_kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: multiple_resources_zookeeper:2181

  multiple_resources_postgres2knex:
    image: postgres:9.6-alpine
    ports:
      - published: 5436
        target: 5432
    environment:
      POSTGRES_DB: dont
      POSTGRES_USER: hurtme
      POSTGRES_PASSWORD: nomore

  multiple_resources_redis:
    image: redis:5.0.3-alpine
    ports:
      - published: 6381
        target: 6379

  multiple_resources_zookeeper:
    image: confluentinc/cp-zookeeper:5.2.2
    ports:
      - published: 2181
        target: 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
