#!/bin/sh

yarn build
git add ./dist
gitCacheDiff="$(git diff --cached --name-only | grep 'dist/' | uniq)"

# In order to prevent infinite commit>post-commit>loop
if [ -z "$gitCacheDiff" ]; then
	exit 0
else
	git commit --amend --no-edit
fi;