#!/bin/sh

##
## If there's buildable updates, compile the code and add it to the commit
##

## 
buildableFilesTouched="$(git diff --cached --name-only | grep 'src/' | uniq)"

## In order to prevent infinite commit>post-commit>loop
if [ -z "$buildableFilesTouched" ]; then
	exit 0
else
	echo "⏳ pre-commit"
	yarn build
	git add ./dist
	echo "✅ pre-commit \n"
fi;
